### ISSUE TITLE
Error decoding response hex

### ISSUE THREAD

**Issue by jmgirgenti** [truedread/pyhulu#4]
The program doesn't work, it shows the error "Error decoding response hex"

**Comment by MythodeaLoL** [comment]
POST need some data like guid/device_id this can be get from cookies, and post need cookies too, current the POST dont sending cookies like hulu site on URL play.hulu.com/config
maybe others thins too.

@truedread u have any news or planed update for this? 
@nyuszika7h

**Comment by rpvcg** [comment]
It works.  Are you using the full "EAB" style video ID (see here: [https://github.com/truedread/pyhulu/pull/2](url)) that is used with the new v4/playlist API?  See also the new "tests" example at the above link.

print(client.load_playlist('EAB::xx::xx::xx')) <- This works.

Of course, if you're using a deejay_device_id code other than 159 (depreciated) or 190, a different device_key might be needed in order to decode the playlist.  Remember also that the new API (for the playlist) returns less information (metadata) than the old API.

**Comment by jmgirgenti** [comment]
@stinkteeth Thanks. Now found.
